dist: bionic

env:
  global:
    - ORG=pkskubeflow
#    - IMAGE_NAME=pkskubeflow/is-controller
    - ISTIO_VERSION=1.7.1
#    - BUILD_WITH_CONTAINER=1
  
services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=${TRAVIS_CPU_ARCH}] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce qemu-user-static
  - wget https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-${TRAVIS_CPU_ARCH}
  - chmod a+x buildx-v0.4.2.linux-${TRAVIS_CPU_ARCH}
  - mkdir -p ~/.docker/cli-plugins
  - mv buildx-v0.4.2.linux-${TRAVIS_CPU_ARCH} ~/.docker/cli-plugins/docker-buildx
  - docker version
  - docker buildx version
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}  
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use
  - docker buildx inspect --bootstrap

script:
  - docker buildx build --push --platform linux/amd64,linux/arm64 -t ${ORG}/istio-proxyv2:${ISTIO_VERSION} -f Dockerfile.proxyv2 .
